import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'gym_backend.settings')
django.setup()

from users.models import DietPlanTemplate

print("=" * 80)
print("CREATING REMAINING 'OTHERS' GOAL TEMPLATES")
print("=" * 80)

# 41-50kg range (1500-1800 cal)
# 51-60kg range (1800-2100 cal)
# 61-70kg range (2100-2400 cal)

# =============================================================================
# 41-50 KG RANGE (1500-1800 calories)
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (41-50kg)",
    goal_type="others",
    calorie_min=1500,
    calorie_max=1800,
    description="7-day balanced vegan maintenance for 41-50kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "12g"}, {"food": "Orange", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Banana", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Tofu", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Black beans", "quantity": "100g"}, {"food": "Carrot", "quantity": "80g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Mango", "quantity": "90g"}, {"food": "Cashews", "quantity": "12g"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}, {"food": "Banana", "quantity": "1 small"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Tofu", "quantity": "100g"}, {"food": "Carrot", "quantity": "90g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Black beans", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "12g"}, {"food": "Mango", "quantity": "60g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "12g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Mango", "quantity": "90g"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Tofu", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Black beans", "quantity": "100g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}, {"food": "Orange", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "12g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}]}
    }
)
print("✓ 41-50kg: General Fitness - Vegan (1500-1800 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (41-50kg)",
    goal_type="others",
    calorie_min=1500,
    calorie_max=1800,
    description="7-day balanced vegetarian maintenance for 41-50kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "200ml"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}, {"food": "Almonds", "quantity": "10g"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Carrot", "quantity": "90g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "snacks": [{"food": "Milk (whole)", "quantity": "200ml"}, {"food": "Walnuts", "quantity": "10g"}, {"food": "Banana", "quantity": "1 small"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}, {"food": "Apple", "quantity": "1 medium"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Milk (whole)", "quantity": "200ml"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Carrot", "quantity": "90g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}, {"food": "Banana", "quantity": "1 small"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "150ml"}, {"food": "Walnuts", "quantity": "10g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Mango", "quantity": "70g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}, {"food": "Orange", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Paneer", "quantity": "80g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}, {"food": "Apple", "quantity": "1 medium"}]}
    }
)
print("✓ 41-50kg: General Fitness - Vegetarian (1500-1800 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (41-50kg)",
    goal_type="others",
    calorie_min=1500,
    calorie_max=1800,
    description="7-day balanced non-veg maintenance for 41-50kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Chicken breast", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Chicken thigh", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Mutton", "quantity": "80g"}, {"food": "Potato", "quantity": "90g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}, {"food": "Banana", "quantity": "1 small"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Mango", "quantity": "60g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Chicken breast", "quantity": "90g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "12g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "90g"}, {"food": "Chicken thigh", "quantity": "80g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "100g"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}, {"food": "Orange", "quantity": "1 medium"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "3 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Mutton", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "110g"}], "dinner": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Mango", "quantity": "70g"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "100g"}, {"food": "Chicken breast", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "3 pieces"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}, {"food": "Orange", "quantity": "1 medium"}]}
    }
)
print("✓ 41-50kg: General Fitness - Non-Veg (1500-1800 cal)")

# =============================================================================
# 51-60 KG RANGE (1800-2100 calories)
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (51-60kg)",
    goal_type="others",
    calorie_min=1800,
    calorie_max=2100,
    description="7-day balanced vegan maintenance for 51-60kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "18g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 small"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Tofu", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Black beans", "quantity": "110g"}, {"food": "Carrot", "quantity": "90g"}], "snacks": [{"food": "Mango", "quantity": "100g"}, {"food": "Cashews", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Mango", "quantity": "100g"}, {"food": "Walnuts", "quantity": "15g"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "15g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Apple", "quantity": "1 small"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Tofu", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Black beans", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Peanuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "15g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Mango", "quantity": "90g"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Apple", "quantity": "1 small"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Mango", "quantity": "100g"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Tofu", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Black beans", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Apple", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "15g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 small"}]}
    }
)
print("✓ 51-60kg: General Fitness - Vegan (1800-2100 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (51-60kg)",
    goal_type="others",
    calorie_min=1800,
    calorie_max=2100,
    description="7-day balanced vegetarian maintenance for 51-60kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Almonds", "quantity": "12g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "snacks": [{"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Walnuts", "quantity": "12g"}, {"food": "Banana", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "12g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Apple", "quantity": "1 medium"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Almonds", "quantity": "12g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "200ml"}, {"food": "Walnuts", "quantity": "12g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Mango", "quantity": "80g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "12g"}, {"food": "Orange", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Paneer", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Apple", "quantity": "1 medium"}]}
    }
)
print("✓ 51-60kg: General Fitness - Vegetarian (1800-2100 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (51-60kg)",
    goal_type="others",
    calorie_min=1800,
    calorie_max=2100,
    description="7-day balanced non-veg maintenance for 51-60kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Chicken breast", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}, {"food": "Banana", "quantity": "1 small"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Chicken thigh", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "12g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Mutton", "quantity": "100g"}, {"food": "Potato", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "12g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Mango", "quantity": "60g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Mango", "quantity": "70g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Chicken breast", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 small"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "60g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "110g"}, {"food": "Chicken thigh", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "120g"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 small"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Mutton", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "120g"}], "dinner": [{"food": "Quinoa", "quantity": "100g"}, {"food": "Chickpeas (cooked)", "quantity": "100g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "12g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Mango", "quantity": "60g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "65g"}, {"food": "Mango", "quantity": "80g"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "120g"}, {"food": "Chicken breast", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "12g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 small"}]}
    }
)
print("✓ 51-60kg: General Fitness - Non-Veg (1800-2100 cal)")

# =============================================================================
# 61-70 KG RANGE (2100-2400 calories)
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (61-70kg)",
    goal_type="others",
    calorie_min=2100,
    calorie_max=2400,
    description="7-day balanced vegan maintenance for 61-70kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "20g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Spinach", "quantity": "100g"}, {"food": "Carrot", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "18g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Peanuts", "quantity": "20g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Black beans", "quantity": "120g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Mango", "quantity": "120g"}, {"food": "Cashews", "quantity": "18g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "85g"}, {"food": "Mango", "quantity": "120g"}, {"food": "Walnuts", "quantity": "18g"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}, {"food": "Carrot", "quantity": "80g"}], "snacks": [{"food": "Orange", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "18g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "18g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Carrot", "quantity": "100g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Black beans", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Peanuts", "quantity": "20g"}, {"food": "Apple", "quantity": "2 medium"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "18g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Chickpeas (cooked)", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Mango", "quantity": "100g"}, {"food": "Walnuts", "quantity": "18g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Apple", "quantity": "1 medium"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Mango", "quantity": "120g"}, {"food": "Almonds", "quantity": "18g"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Black beans", "quantity": "120g"}, {"food": "Carrot", "quantity": "100g"}, {"food": "Spinach", "quantity": "80g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "20g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Apple", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "85g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "18g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "18g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]}
    }
)
print("✓ 61-70kg: General Fitness - Vegan (2100-2400 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (61-70kg)",
    goal_type="others",
    calorie_min=2100,
    calorie_max=2400,
    description="7-day balanced vegetarian maintenance for 61-70kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}, {"food": "Carrot", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Carrot", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "15g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Milk (whole)", "quantity": "250ml"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Carrot", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Milk (whole)", "quantity": "200ml"}, {"food": "Walnuts", "quantity": "15g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Mango", "quantity": "90g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "15g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "15g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Paneer", "quantity": "100g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]}
    }
)
print("✓ 61-70kg: General Fitness - Vegetarian (2100-2400 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (61-70kg)",
    goal_type="others",
    calorie_min=2100,
    calorie_max=2400,
    description="7-day balanced non-veg maintenance for 61-70kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Chicken breast", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}, {"food": "Carrot", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "15g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Chicken thigh", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Mutton", "quantity": "110g"}, {"food": "Potato", "quantity": "110g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "15g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Mango", "quantity": "70g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Mango", "quantity": "80g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Chicken breast", "quantity": "120g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "18g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Banana", "quantity": "2 medium"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "70g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "130g"}, {"food": "Chicken thigh", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "140g"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "15g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "2 medium"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Mutton", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Quinoa", "quantity": "120g"}, {"food": "Chickpeas (cooked)", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "15g"}, {"food": "Apple", "quantity": "1 medium"}, {"food": "Mango", "quantity": "70g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Mango", "quantity": "90g"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "140g"}, {"food": "Chicken breast", "quantity": "120g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "4 pieces"}, {"food": "Lentils (cooked)", "quantity": "110g"}, {"food": "Carrot", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "15g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "2 medium"}]}
    }
)
print("✓ 61-70kg: General Fitness - Non-Veg (2100-2400 cal)")

print("\n" + "=" * 80)
print("✅ ALL 'OTHERS' GOAL TEMPLATES CREATED!")
print("=" * 80)
templates = DietPlanTemplate.objects.filter(goal_type='others').order_by('calorie_min', 'name')
for t in templates:
    print(f"  {t.calorie_min:4d}-{t.calorie_max:4d} cal | {t.name}")

print(f"\nTotal: {templates.count()} templates")
print("\nWeight Coverage:")
print("  30-40kg → 1200-1500 cal")
print("  41-50kg → 1500-1800 cal")
print("  51-60kg → 1800-2100 cal")
print("  61-70kg → 2100-2400 cal")
print("\n✅ General fitness users now have complete diet plan coverage!")
