import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'gym_backend.settings')
django.setup()

from users.models import DietPlanTemplate

print("="*80)
print("CREATING ADDITIONAL 'OTHERS' GOAL TEMPLATES BY WEIGHT RANGE")
print("="*80)

# =============================================================================
# 20-30 KG RANGE (1000-1200 calories) - Very light individuals
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (20-30kg)",
    goal_type="others",
    calorie_min=1000,
    calorie_max=1200,
    description="7-day balanced vegan maintenance for 20-30kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "80g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Banana", "quantity": "1 small"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Tofu", "quantity": "60g"}, {"food": "Mixed vegetables", "quantity": "80g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Black beans", "quantity": "70g"}, {"food": "Carrot", "quantity": "60g"}], "snacks": [{"food": "Orange", "quantity": "1 small"}, {"food": "Peanuts", "quantity": "10g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Mango", "quantity": "60g"}, {"food": "Cashews", "quantity": "8g"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Lentils (cooked)", "quantity": "80g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Banana", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Orange", "quantity": "1 small"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Tofu", "quantity": "60g"}, {"food": "Carrot", "quantity": "70g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Black beans", "quantity": "70g"}, {"food": "Mixed vegetables", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Orange", "quantity": "1 small"}, {"food": "Peanuts", "quantity": "10g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "80g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Banana", "quantity": "1 small"}, {"food": "Cashews", "quantity": "8g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Mango", "quantity": "60g"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Tofu", "quantity": "60g"}, {"food": "Mixed vegetables", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Black beans", "quantity": "70g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "80g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Orange", "quantity": "1 small"}, {"food": "Peanuts", "quantity": "10g"}]}
    }
)
print("✓ 20-30kg: General Fitness - Vegan (1000-1200 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (20-30kg)",
    goal_type="others",
    calorie_min=1000,
    calorie_max=1200,
    description="7-day balanced vegetarian maintenance for 20-30kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "35g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Milk (whole)", "quantity": "150ml"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "70g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Orange", "quantity": "1 small"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Carrot", "quantity": "60g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "snacks": [{"food": "Milk (whole)", "quantity": "150ml"}, {"food": "Almonds", "quantity": "8g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Cashews", "quantity": "8g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "70g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Orange", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Milk (whole)", "quantity": "150ml"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Carrot", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "35g"}, {"food": "Orange", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Lentils (cooked)", "quantity": "70g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Banana", "quantity": "1 small"}, {"food": "Milk (whole)", "quantity": "100ml"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Mango", "quantity": "50g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "70g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Carrot", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Cashews", "quantity": "8g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "70g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Paneer", "quantity": "50g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Orange", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]}
    }
)
print("✓ 20-30kg: General Fitness - Vegetarian (1000-1200 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (20-30kg)",
    goal_type="others",
    calorie_min=1000,
    calorie_max=1200,
    description="7-day balanced non-veg maintenance for 20-30kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "30g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Chicken breast", "quantity": "60g"}, {"food": "Broccoli", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "60g"}, {"food": "Spinach", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Orange", "quantity": "1 small"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chicken thigh", "quantity": "50g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "60g"}, {"food": "Carrot", "quantity": "60g"}], "snacks": [{"food": "Banana", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "35g"}, {"food": "Orange", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Mutton", "quantity": "50g"}, {"food": "Potato", "quantity": "60g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Lentils (cooked)", "quantity": "60g"}, {"food": "Broccoli", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Mango", "quantity": "40g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Chicken breast", "quantity": "60g"}, {"food": "Spinach", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "60g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "snacks": [{"food": "Orange", "quantity": "1 small"}, {"food": "Peanuts", "quantity": "10g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "30g"}, {"food": "Banana", "quantity": "1 small"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chicken thigh", "quantity": "50g"}, {"food": "Broccoli", "quantity": "60g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "60g"}, {"food": "Carrot", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Cashews", "quantity": "8g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Orange", "quantity": "1 small"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Mutton", "quantity": "50g"}, {"food": "Mixed vegetables", "quantity": "70g"}], "dinner": [{"food": "Quinoa", "quantity": "60g"}, {"food": "Chickpeas (cooked)", "quantity": "60g"}, {"food": "Spinach", "quantity": "60g"}], "snacks": [{"food": "Banana", "quantity": "1 small"}, {"food": "Almonds", "quantity": "8g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "35g"}, {"food": "Mango", "quantity": "50g"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "80g"}, {"food": "Chicken breast", "quantity": "60g"}, {"food": "Broccoli", "quantity": "60g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "60g"}, {"food": "Carrot", "quantity": "60g"}], "snacks": [{"food": "Apple", "quantity": "1 small"}, {"food": "Walnuts", "quantity": "8g"}]}
    }
)
print("✓ 20-30kg: General Fitness - Non-Veg (1000-1200 cal)")

# =============================================================================
# 31-40 KG RANGE (1200-1400 calories) - Overlaps with existing 30-40kg
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (31-40kg)",
    goal_type="others",
    calorie_min=1200,
    calorie_max=1400,
    description="7-day balanced vegan maintenance for 31-40kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "12g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Banana", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Tofu", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Black beans", "quantity": "80g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "12g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Mango", "quantity": "70g"}, {"food": "Cashews", "quantity": "10g"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Tofu", "quantity": "80g"}, {"food": "Carrot", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Black beans", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "12g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Mango", "quantity": "70g"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Tofu", "quantity": "80g"}, {"food": "Mixed vegetables", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Black beans", "quantity": "80g"}, {"food": "Carrot", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "55g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "100g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chickpeas (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "12g"}]}
    }
)
print("✓ 31-40kg: General Fitness - Vegan (1200-1400 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (31-40kg)",
    goal_type="others",
    calorie_min=1200,
    calorie_max=1400,
    description="7-day balanced vegetarian maintenance for 31-40kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "180ml"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chickpeas (cooked)", "quantity": "85g"}, {"food": "Carrot", "quantity": "70g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "snacks": [{"food": "Milk (whole)", "quantity": "180ml"}, {"food": "Almonds", "quantity": "10g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Milk (whole)", "quantity": "180ml"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Chickpeas (cooked)", "quantity": "85g"}, {"food": "Carrot", "quantity": "70g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Milk (whole)", "quantity": "150ml"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "1 piece"}, {"food": "Mango", "quantity": "60g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "85g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "50g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "90g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Paneer", "quantity": "65g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]}
    }
)
print("✓ 31-40kg: General Fitness - Vegetarian (1200-1400 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (31-40kg)",
    goal_type="others",
    calorie_min=1200,
    calorie_max=1400,
    description="7-day balanced non-veg maintenance for 31-40kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Chicken breast", "quantity": "70g"}, {"food": "Broccoli", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "80g"}, {"food": "Spinach", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Orange", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chicken thigh", "quantity": "65g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Chickpeas (cooked)", "quantity": "75g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Mutton", "quantity": "65g"}, {"food": "Potato", "quantity": "75g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Lentils (cooked)", "quantity": "75g"}, {"food": "Broccoli", "quantity": "80g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Mango", "quantity": "50g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Chicken breast", "quantity": "70g"}, {"food": "Spinach", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "75g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "snacks": [{"food": "Orange", "quantity": "1 medium"}, {"food": "Peanuts", "quantity": "10g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "40g"}, {"food": "Banana", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Quinoa", "quantity": "80g"}, {"food": "Chicken thigh", "quantity": "65g"}, {"food": "Broccoli", "quantity": "80g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "90g"}, {"food": "Lentils (cooked)", "quantity": "75g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "10g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "2 slices"}, {"food": "Eggs (scrambled)", "quantity": "2 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Mutton", "quantity": "65g"}, {"food": "Mixed vegetables", "quantity": "90g"}], "dinner": [{"food": "Quinoa", "quantity": "70g"}, {"food": "Chickpeas (cooked)", "quantity": "75g"}, {"food": "Spinach", "quantity": "80g"}], "snacks": [{"food": "Banana", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "10g"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "45g"}, {"food": "Mango", "quantity": "60g"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "90g"}, {"food": "Chicken breast", "quantity": "70g"}, {"food": "Broccoli", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "2 pieces"}, {"food": "Lentils (cooked)", "quantity": "75g"}, {"food": "Carrot", "quantity": "70g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Walnuts", "quantity": "10g"}]}
    }
)
print("✓ 31-40kg: General Fitness - Non-Veg (1200-1400 cal)")

# =============================================================================
# 70-80 KG RANGE (2400-2700 calories) - Heavier individuals
# =============================================================================

DietPlanTemplate.objects.create(
    name="General Fitness - Vegan (70-80kg)",
    goal_type="others",
    calorie_min=2400,
    calorie_max=2700,
    description="7-day balanced vegan maintenance for 70-80kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "95g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "25g"}, {"food": "Peanut butter", "quantity": "15g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Lentils (cooked)", "quantity": "150g"}, {"food": "Tofu", "quantity": "100g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Chickpeas (cooked)", "quantity": "140g"}, {"food": "Avocado", "quantity": "90g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "30g"}, {"food": "Dates", "quantity": "50g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Peanut butter", "quantity": "25g"}, {"food": "Banana", "quantity": "2 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Black beans", "quantity": "150g"}, {"food": "Sweet potato", "quantity": "160g"}, {"food": "Mixed vegetables", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Tofu", "quantity": "100g"}], "snacks": [{"food": "Mango", "quantity": "150g"}, {"food": "Walnuts", "quantity": "30g"}, {"food": "Orange", "quantity": "2 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "100g"}, {"food": "Mango", "quantity": "130g"}, {"food": "Walnuts", "quantity": "25g"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Chickpeas (cooked)", "quantity": "150g"}, {"food": "Avocado", "quantity": "80g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Orange", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "30g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Almond butter", "quantity": "25g"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Lentils (cooked)", "quantity": "150g"}, {"food": "Sweet potato", "quantity": "130g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Black beans", "quantity": "140g"}, {"food": "Avocado", "quantity": "90g"}], "snacks": [{"food": "Banana", "quantity": "3 medium"}, {"food": "Cashews", "quantity": "30g"}, {"food": "Dates", "quantity": "40g"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "95g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Peanut butter", "quantity": "20g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "150g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Mango", "quantity": "140g"}, {"food": "Walnuts", "quantity": "30g"}, {"food": "Apple", "quantity": "2 medium"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Peanut butter", "quantity": "25g"}, {"food": "Mango", "quantity": "110g"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Lentils (cooked)", "quantity": "150g"}, {"food": "Avocado", "quantity": "80g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Black beans", "quantity": "140g"}, {"food": "Sweet potato", "quantity": "130g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "30g"}, {"food": "Orange", "quantity": "2 medium"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "100g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "25g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Chickpeas (cooked)", "quantity": "150g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Tofu", "quantity": "120g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Apple", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "30g"}, {"food": "Dates", "quantity": "50g"}]}
    }
)
print("✓ 70-80kg: General Fitness - Vegan (2400-2700 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Vegetarian (70-80kg)",
    goal_type="others",
    calorie_min=2400,
    calorie_max=2700,
    description="7-day balanced vegetarian maintenance for 70-80kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "85g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Milk (whole)", "quantity": "300ml"}, {"food": "Almonds", "quantity": "18g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Paneer", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}, {"food": "Ghee", "quantity": "12g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Milk (whole)", "quantity": "200ml"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Butter", "quantity": "18g"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Chickpeas (cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Paneer", "quantity": "110g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Milk (whole)", "quantity": "300ml"}, {"food": "Walnuts", "quantity": "28g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "90g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "22g"}, {"food": "Milk (whole)", "quantity": "250ml"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Paneer", "quantity": "110g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Orange", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Almonds", "quantity": "28g"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Butter", "quantity": "18g"}, {"food": "Milk (whole)", "quantity": "300ml"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Chickpeas (cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "85g"}, {"food": "Orange", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Paneer", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Milk (whole)", "quantity": "300ml"}, {"food": "Walnuts", "quantity": "28g"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "3 pieces"}, {"food": "Mango", "quantity": "100g"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Chickpeas (cooked)", "quantity": "140g"}, {"food": "Paneer", "quantity": "100g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Orange", "quantity": "2 medium"}, {"food": "Milk (whole)", "quantity": "200ml"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "90g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Almonds", "quantity": "22g"}, {"food": "Milk (whole)", "quantity": "250ml"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Paneer", "quantity": "110g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Lentils (cooked)", "quantity": "140g"}, {"food": "Curd", "quantity": "180g"}], "snacks": [{"food": "Orange", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Walnuts", "quantity": "28g"}]}
    }
)
print("✓ 70-80kg: General Fitness - Vegetarian (2400-2700 cal)")

DietPlanTemplate.objects.create(
    name="General Fitness - Non-Veg (70-80kg)",
    goal_type="others",
    calorie_min=2400,
    calorie_max=2700,
    description="7-day balanced non-veg maintenance for 70-80kg",
    meals_data={
        "monday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}, {"food": "Almonds", "quantity": "22g"}], "lunch": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Chicken breast", "quantity": "140g"}, {"food": "Broccoli", "quantity": "100g"}, {"food": "Ghee", "quantity": "12g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Lentils (cooked)", "quantity": "130g"}, {"food": "Chicken curry", "quantity": "110g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Apple", "quantity": "1 medium"}]},
        "tuesday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "4 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Chicken thigh", "quantity": "130g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Fish", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "28g"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}]},
        "wednesday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Orange", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Mutton", "quantity": "130g"}, {"food": "Potato", "quantity": "130g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Chicken breast", "quantity": "140g"}, {"food": "Broccoli", "quantity": "100g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "1 piece"}]},
        "thursday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "4 pieces"}, {"food": "Mango", "quantity": "90g"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Chicken curry", "quantity": "140g"}, {"food": "Spinach", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Fish", "quantity": "130g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "snacks": [{"food": "Orange", "quantity": "2 medium"}, {"food": "Peanuts", "quantity": "35g"}, {"food": "Banana", "quantity": "2 medium"}]},
        "friday": {"breakfast": [{"food": "Oats", "quantity": "75g"}, {"food": "Banana", "quantity": "2 medium"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Quinoa", "quantity": "150g"}, {"food": "Chicken thigh", "quantity": "130g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Rice (brown, cooked)", "quantity": "160g"}, {"food": "Mutton", "quantity": "120g"}, {"food": "Carrot", "quantity": "110g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Almonds", "quantity": "28g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}]},
        "saturday": {"breakfast": [{"food": "Bread (whole wheat)", "quantity": "4 slices"}, {"food": "Eggs (scrambled)", "quantity": "4 pieces"}, {"food": "Orange", "quantity": "1 medium"}], "lunch": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Chicken breast", "quantity": "140g"}, {"food": "Mixed vegetables", "quantity": "130g"}], "dinner": [{"food": "Quinoa", "quantity": "140g"}, {"food": "Fish", "quantity": "130g"}, {"food": "Spinach", "quantity": "100g"}], "snacks": [{"food": "Banana", "quantity": "2 medium"}, {"food": "Walnuts", "quantity": "28g"}, {"food": "Eggs (boiled)", "quantity": "2 pieces"}]},
        "sunday": {"breakfast": [{"food": "Oats", "quantity": "80g"}, {"food": "Mango", "quantity": "110g"}, {"food": "Eggs (boiled)", "quantity": "3 pieces"}], "lunch": [{"food": "Rice (white, cooked)", "quantity": "160g"}, {"food": "Chicken curry", "quantity": "140g"}, {"food": "Broccoli", "quantity": "100g"}], "dinner": [{"food": "Roti (wheat)", "quantity": "5 pieces"}, {"food": "Mutton", "quantity": "120g"}, {"food": "Carrot", "quantity": "110g"}], "snacks": [{"food": "Apple", "quantity": "1 medium"}, {"food": "Cashews", "quantity": "28g"}, {"food": "Orange", "quantity": "1 medium"}, {"food": "Banana", "quantity": "1 medium"}]}
    }
)
print("✓ 70-80kg: General Fitness - Non-Veg (2400-2700 cal)")

print("\n" + "="*80)
print("✅ ADDITIONAL 'OTHERS' GOAL TEMPLATES CREATED!")
print("="*80)
templates = DietPlanTemplate.objects.filter(goal_type='others').order_by('calorie_min', 'name')
print(f"\nAll 'others' goal templates:")
for t in templates:
    print(f"  {t.calorie_min:4d}-{t.calorie_max:4d} cal | {t.name}")
print(f"\nTotal: {templates.count()} templates")
print("\nWeight Coverage:")
print("  20-30kg → 1000-1200 cal")
print("  31-40kg → 1200-1400 cal")
print("  30-40kg → 1200-1500 cal (existing)")
print("  41-50kg → 1500-1800 cal (existing)")
print("  51-60kg → 1800-2100 cal (existing)")
print("  61-70kg → 2100-2400 cal (existing)")
print("  70-80kg → 2400-2700 cal")
print("\n✅ Complete weight range coverage for general fitness users!")
