# Generated by Django 4.2.7 on 2026-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "emailid",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email ID"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "User Login",
                "verbose_name_plural": "User Logins",
                "db_table": "userlogin",
                "ordering": ["-created_at"],
            },
        ),
    ]
