# Generated by Django 4.2.7 on 2026-01-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlogin",
            name="role",
            field=models.CharField(default="user", max_length=50, verbose_name="Role"),
        ),
    ]
