# Generated by Django 4.2.7 on 2026-01-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "current_weight",
                    models.FloatField(verbose_name="Current Weight (kg)"),
                ),
                (
                    "current_height",
                    models.FloatField(verbose_name="Current Height (cm)"),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("weight_gain", "Weight Gain"),
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        verbose_name="Goal",
                    ),
                ),
                ("target_weight", models.FloatField(verbose_name="Target Weight (kg)")),
                (
                    "target_months",
                    models.IntegerField(
                        choices=[
                            (1, "1 Month"),
                            (2, "2 Months"),
                            (3, "3 Months"),
                            (6, "6 Months"),
                            (8, "8 Months"),
                            (12, "1 Year"),
                        ],
                        verbose_name="Target Months",
                    ),
                ),
                (
                    "workout_time",
                    models.CharField(
                        choices=[
                            ("morning", "4 AM to 11 AM"),
                            ("evening", "4 PM to 11 PM"),
                        ],
                        max_length=10,
                        verbose_name="Workout Time",
                    ),
                ),
                (
                    "diet_preference",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        verbose_name="Diet Preference",
                    ),
                ),
                (
                    "food_allergies",
                    models.TextField(
                        blank=True, null=True, verbose_name="Food Allergies"
                    ),
                ),
                (
                    "health_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Health Conditions"
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="Payment Status"),
                ),
                (
                    "payment_amount",
                    models.IntegerField(default=0, verbose_name="Payment Amount"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="users.userlogin",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profile",
            },
        ),
    ]
