# Generated by Django 4.2.7 on 2026-01-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(
                default="0000000000", max_length=10, verbose_name="Mobile Number"
            ),
        ),
    ]
