# Generated by Django 4.2.7 on 2026-01-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_users",
                to="users.trainer",
                verbose_name="Assigned Trainer",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Payment Method"
            ),
        ),
    ]
