# Generated by Django 4.2.7 on 2026-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_assigned_trainer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="certification",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Certification"
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="goal_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_gain", "Weight Gain"),
                    ("weight_loss", "Weight Loss"),
                    ("muscle_gain", "Muscle Gain"),
                    ("others", "Others"),
                ],
                max_length=20,
                null=True,
                verbose_name="Assigned Goal Category",
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
