# Generated by Django 4.2.7 on 2026-01-21 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_diet_type_to_food_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Video Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "video_file",
                    models.FileField(
                        upload_to="workout_videos/", verbose_name="Video File"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="video_thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight_gain", "Weight Gain"),
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("muscle_building", "Muscle Building"),
                            ("others", "General Fitness"),
                        ],
                        max_length=50,
                        verbose_name="Goal Type",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner (0-10kg difference)"),
                            ("advanced", "Advanced (11-30kg difference)"),
                        ],
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "min_weight_difference",
                    models.IntegerField(
                        default=0, verbose_name="Min Weight Difference (kg)"
                    ),
                ),
                (
                    "max_weight_difference",
                    models.IntegerField(
                        default=10, verbose_name="Max Weight Difference (kg)"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_videos",
                        to="users.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Video",
                "verbose_name_plural": "Workout Videos",
                "db_table": "workout_video",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Trainer's Note"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Recommended At"
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_recommendations",
                        to="users.trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_videos",
                        to="users.userprofile",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="users.workoutvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Recommendation",
                "verbose_name_plural": "Video Recommendations",
                "db_table": "video_recommendation",
                "ordering": ["-created_at"],
                "unique_together": {("video", "user")},
            },
        ),
    ]
