# Generated by Django 4.2.7 on 2026-01-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_workoutvideo_videorecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutvideo",
            name="day_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Day Number (for daily progression)"
            ),
        ),
        migrations.AddField(
            model_name="workoutvideo",
            name="uploaded_via",
            field=models.CharField(
                choices=[("web", "Web Upload"), ("bulk", "Bulk/Admin Upload")],
                default="web",
                max_length=10,
                verbose_name="Upload Type",
            ),
        ),
    ]
